version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
      #- ../sql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isucari
      MYSQL_USER: isucari
      MYSQL_PASSWORD: isucari
    networks:
      - backend
    ports:
      - "3306"

  api-server:
    build: ../go
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://db:3306
    volumes:
      - ../public:/home/isucon/isucari/webapp/public
    environment:
      MYSQL_DBNAME: isucari
      MYSQL_USER: isucari
      MYSQL_PASS: isucari
      MYSQL_HOST: db
      SERVER_PORT: 8000
    networks:
      - backend
    depends_on:
      - db
    command: /home/isucon/isucari/webapp/go/isucari

  web:
    build: ../nginx
    volumes:
      - ../../provisioning/roles/webapp.nginx/files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../provisioning/roles/webapp.nginx/files/etc/nginx/sites-available/isucari.conf:/etc/nginx/sites-enabled/isucari.conf
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - api-server

networks:
  backend:
