version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ../sql:/home/isucon/isucari/webapp/sql
    #  - ../mysql/db:/docker-entrypoint-initdb.d
    #  - ../logs/mysql:/var/log/mysql
    #  - ../../provisioning/ansible/roles/web-bootstrap/files/my.cnf:/etc/mysql/conf.d/my.cnf
    #  - ../../provisioning/ansible/roles/web-bootstrap/files/slow-mysqld.cnf:/etc/mysql/conf.d/slowquery.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isucari
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    ports:
      - "3306:3306"
  api-server:
    build: ../go
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://mysql:3306
    volumes:
      - ../public:/home/isucon/isucari/webapp/public
    #  - ../mysql/db:/go/src/mysql/db
    #  - ../fixture:/go/src/fixture
    environment:
      MYSQL_DBNAME: isucari
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
      MYSQL_HOST: mysql
      SERVER_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: /home/isucon/isucari/webapp/go/isucari
